### PR TITLE
Added thread locking to Source.gets method when there is no input MIDI data on the input queue; unlocks on MIDI data received

### PR DESCRIPTION
**Pull request by javier-sy**
Hello Ari,

I have done this change to your ffi-coremidi gem in order to lock the thread asking for MIDI input until there is some data. This allows to reduce CPU usage but changes the current semantics of gets method. I needed this new behavior using UniMIDI but I don't know if this change is useful for everybody.

Maybe it would be useful to have a configuration option in UniMIDI selecting the behavior of ffi-coremidi (thread-locking gets vs non-locking-thread gets). This would require some UniMIDI modifications and some ffi-coremidi configuration that I have not implemented. Probably this would introduce a compatibility problem between Mac, Linux, Windows because of the gets semantic change.

I can make further changes on UniMIDI or ffi-coremidi. Just let me know what you think.

Regards

### CODE REVIEW

**Comment by javier-sy** [comment]
I've also added the buffer size limit change you made 2 years ago. Both changes allow better CPU usage.

**Comment by arirusso** [comment]
This looks great, sorry for the delay. Will test in the next couple of days and merge. Thank you for the contribution

**Comment by arirusso** [comment]
@javier-sy Why do you say this changes the semantics of the gets method?

**Comment by javier-sy** [comment]
@arirusso , If I remember correctly the original gets method always returns immediately if there is no data (it returns []) . The modified version returns only when there is new data. If there is no new data it will sleep until the new data comes. Maybe some users code depends on gets returning immediately. This change could make their code didn't work as expected.

**Comment by arirusso** [comment]
@javier-sy Unless I'm misunderstanding, that's actually how the original works too. It was modeled on the Ruby IO `gets` method.  Sort of.  It reads until the buffer is empty

**Comment by javier-sy** [comment]
@arirusso Queue has a locking behavior when using pop method but in fill_buffer method when the queue is already empty it doesn't locks waiting for the next incoming data. The difference is that in the original version, when the queue is already empty, it returns [] immediately. In the modified version when the queue is empty it waits until it arrives some data.

**Comment by arirusso** [comment]
@javier-sy Thank you so much for this work, apologies again at my slowness in getting it merged. More appreciated than that would indicate

**Comment by javier-sy** [comment]
@arirusso, great it has been useful. If you consider it appropriate on your acknowledgements policy maybe you could cite the contribution. 

As I had no response on 2020 I had to created a fork project with another name to continue my work. It seems it was included in the merge request. Sorry for that!

**Pull request closed without merging**
